### ISSUE TITLE
My personal experience, for reference only

### ISSUE THREAD

**Issue by lopo12123** [naomijub/blog#1]
https://github.com/naomijub/blog/blob/9e7fffbc6bc0ec5a4a69935213f10f7f17953973/src/code/merge_sorted_arrays.md?plain=1#L113

In fact, the running time and consumption of the same code submitted to Leetcode in the morning/noon/evening may vary greatly, which seems to depend on the situation of the Leetcode server at the time of submission; even the same code submitted one minute apart may have some obvious differences.
I don't know if this writing method is really more efficient than the for loop, but the comparison through the consumption of Leetcode does not seem so convincing (at least not to the order of magnitude that really has a difference)

**Comment by naomijub** [comment]
Well, this was benchmarked multiple times in a controlled environment with cargo bench as well. I only used leetcode to check if all cases passed. However, thanks for the feedback, I will make it more clear how the benchmark was executed, just read it again and understood from where the confusion came.

About the algorithm itself, my initial only goal was to make it more functional like and not have worst performance. Possibly the laziness and compiler early exit were the reasons of the improvement

**Comment by naomijub** [comment]
Updated with a more descriptive benchmark explanation. Thanks
